### ISSUE TITLE
Building Speed

### ISSUE THREAD

**Issue by ctark** [jrbudda/Builder#1]
Hey,

Great plugins!

Would it be possible to think about adding a building speed.

Say if you will be having them build something over and over, maybe have them building at 1/2 the speed they do now, or 1/4...

Probably wouldn't be too hard to implement, but would be cool, especially if they are building small structures, it could be more realistic...

Thanks!
Ctark

**Comment by jrbudda** [comment]
Setting the /npc speed to a value lower than 1 will slow him down a little. The maximum time between blocks will be 2 seconds, no matter what walking speed. This will be expanded in future versions, there are some pathfinding issues to work out still.

**Comment by adamwbb** [comment]
the faster you put npc speed the longer it wll take to place a block manly bcause the npc will keep overshooting its target and falling off

**Comment by jrbudda** [comment]
"/builder timeout 0" is the preferred way to make the builder build as fast as possible, changing the walking speed is not recommened for the reasons you have stated.
