### ISSUE TITLE
Ability to control direction of build

### ISSUE THREAD

**Issue by seanth** [jrbudda/Builder#11]
I'd like there to be a way to control the direction in which something is built. For example, I would like a builder to build a staircase down into the ground. Right now, the builder magically disappears down into the ground and emerges from the bottom up. It's possible to have the builder dig down first and the build up, but that doesn't seem realistic.

**Comment by jrbudda** [comment]
I don't foresee implementing that option. There are extremely few situations where you want something built top-down. 

I'm not sure what you mean by 'doesn't seem realistic' in regards to the excavate option, that's how things underground are built. The builder will excavate from the top-down, then build from the bottom-up.
