### ISSUE TITLE
Builder Info, Mark, Build off by 1

### ISSUE THREAD

**Issue by Eliasar** [jrbudda/Builder#16]
In testing the Builder for our server, I noticed some odd behavior. Here's the builder info:

Schematic: 6 wide, 10 long, 15 tall
Origin: x:-1508, y:70, z:616

Steps to reproduce:
1. I marked the builder's origin by using {/builder origin me} while I was at x:-1507.43, y:71.62, z:616.48.
2. I then let the builder build the schematic {/builder build linear}.
3. After he's done building, I mark the outline again with {/builder mark}
4. The attached picture shows the build, the mark, and green wool indicating where the corners of the actual schematic are. Also, red wool indicates where the origin was set to, and blue wool indicates where the builder info origin is notated at.

![Jobs - Builder Info Mark Build issue](https://f.cloud.github.com/assets/200301/150008/82ef5e44-7541-11e2-9283-7bf496a60e82.png)

**Comment by jrbudda** [comment]
I've reproduced the issue with the marks and schematic being off by 1 from each other. I cannot reproduce the origin being different than the one set. If I'm reading your information correctly, you were at x:-1507.43, y:71.62, z:616.48 (the red wool?). when you ran /builder origin me, and it set the origin to x:-1508, y:70, z:616, which is correct. What is the location of the blue wool?

**Comment by Eliasar** [comment]
I set the builder's origin {/builder origin me} while standing on the red wool, x:-1507.43, y:71.62, z:616.48.

The location of the blue wool and the builder info are the same: x:-1508, y:71.62, z:616

**Comment by jrbudda** [comment]
x:-1507.43, y:71.62, z:616.48. as a block address is x:-1508, y:71.62, z:616

while standing on the blue wool, hit f3 and check what X block you are on. It should tell you something like -1508.123654654 (-1509), which is block -1509.

**Comment by Eliasar** [comment]
Oh ok. The red wool is a x:-1507.43 (-1508) y:71.62 (70) z:616.48 (616).
The blue wool is at x: (-1509), y:(70), z:(616)

Mike Wells

**Comment by jrbudda** [comment]
kk, so the origin is correct. I've fixed the other issue. Here is a jar if you want it. http://www.sendspace.com/file/gh4fvp

Note that this build removes support for Denizen 0.76, if you were using it. (likely not, as it is no longer compatible with latest citizens2)
