### ISSUE TITLE
Please give option of requiring unobtainable

### ISSUE THREAD

**Issue by CosmicVoyager** [jrbudda/Builder#18]
Greetings,

"Unobtainable blocks, or blocks only obtainable via Silk Touch or Creative Mode, are supplied by giving their normal drop type."

Can you give the option of requiring the actual item please. It is integral to my economy.

Thanks

**Comment by jrbudda** [comment]
Sure, that's a good idea. See if this suits your needs http://www.sendspace.com/file/wc6oe6

Let it make a new config.yml and set RequireUnobtainableBlocks to True.

The only blocks I'm filtering out are Air and Portals, lemme know if that needs more tweaking.

**Comment by CosmicVoyager** [comment]
Thank you very much :-)
