### ISSUE TITLE
Question: Multiple builders per schematic

### ISSUE THREAD

**Issue by wolfbane8653** [jrbudda/Builder#21]
Someone posted:
"multiple builders with the same schematic and different build patterns will allow up to 4 builders at once, or split the schematic."

I have a extremely large schematic being built and it has taken over 24 hours and it's no where to getting complete. I have changed the Movetimeout to 0.1 and the walking speed to 10. The one builder is moving extremely fast but I feel if I can start a second or a third builder to the project it would get completed much faster. Is there a way I can add a second builder to the same project that is currently being built by the first builder?

**Comment by jrbudda** [comment]
check the faq on the wiki page
