### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by moofasa78** [jrbudda/Builder#31]
Hey, i got a small problem with your plugin... every time i do /builder build it won't work

heres my consol: http://pastebin.com/gZUQ0TvA

Mc: 1.7.2
citizens2: 1.7.2
Builder: Latest

This have happened since 5 months ago, when it was 1.6.4 and 1.6.2 too.

**Comment by jrbudda** [comment]
Get the actual latest build from the wiki page. The build for CB 1.7.2 is still in the approval queue on bukkit.
