### ISSUE TITLE
[Request] Ability to just "paste" schematic via NPC

### ISSUE THREAD

**Issue by JumanjiCraft** [jrbudda/Builder#5]
Just a shoutout, great plugin! Builder is really cool!

I have a few quests I want to script where I want to instantly reset an area, however in order to do so I need "builder" to just instantly reset the schematic area rather than build it by hand. Is it possible to have the ability for the builder to on a command run just paste the schematic he has saved in his system?

**Comment by jrbudda** [comment]
No, that's what worldedit does..
