### ISSUE TITLE
When the OP logs out the Builder stops building and becomes Idle. How do you resume?

### ISSUE THREAD

**Issue by sylbhann** [jrbudda/Builder#6]
Is there a resume (/builder resume) when you've selected the NPC to help this?

**Comment by jrbudda** [comment]
Are you using 0.6?

**Comment by sylbhann** [comment]
no, it's from this link: http://dev.bukkit.org/server-mods/builder-citizens2/files/7-builder-0-5-1/

**Comment by jrbudda** [comment]
Try it with .6 on the downloads page here on github.
