### ISSUE TITLE
0.6 Preview, supply mode.

### ISSUE THREAD

**Issue by mrdragalion** [jrbudda/Builder#8]
Fire (51) and Water (09) are needed by the NPC to build some buildings in Supply mode.

And without a /give or /item command these are unattainable. Would it be possible to look in to maybe excluding these or setting it to.

Fire > needs a Flint and Timber
Water > needs (#of water) water buckets?

**Comment by jrbudda** [comment]
Hmm fire and water are both supposed to be ignored, will look into it, thanks

**Comment by mrdragalion** [comment]
Not at all a problem.

I noticed it when using the latest (#3) of 0.6. I used the pre added house.schem and he needed 1 fire.

**Comment by jrbudda** [comment]
I fixed fire, are you sure about the water? all liquids should be ignored already.

**Comment by mrdragalion** [comment]
Ignore the water, just the fire.

Must of been my eyes on something else.

**Comment by jrbudda** [comment]
OK cool, i fixed up 2 other minor items and that should do it for releasing .6, thanks!

**Comment by mrdragalion** [comment]
No problem!
